MUI framework installed and skeleton form create
Code-the-Dream-School/dd-prac-team4-front pull request #5
Opened 2023-08-03 21:39 UTC by dayofthetech

First PR after accept invitation.

2023-08-03 22:11 UTC, akosasante requested changes
Looks great! I would encourage you to also include a short blurb in the `docs` folder so that the other frontend collaborators have a general idea of how to get started using Material UI. Can be an explanation of the library or links to any resources or docs that you think will be helpful.

2023-08-03 22:11 UTC, akosasante commented on package.json
> +    "@emotion/styled": "^11.11.0",
Since this repo already has `styled-components` installed, and `emotion` is a simliar library, maybe we just stick with `styled-components`? If you have an inkling to try `emotion` instead, then that's totally fine, but we should not have both installed since it may eventually cause some styling conflicts.

**If we want to keep `styled-components`:**

[https://mui.com/material-ui/getting-started/installation/#with-styled-components](https://mui.com/material-ui/getting-started/installation/#with-styled-components)

```
# uninstall emotion libraries
npm rm @emotion/react @emotion/styled

# install material ui styled-components helper
npm i -S @mui/styled-engine-sc
```

**If we want to keep `emotion`:**

```
# uninstall styled-components
npm rm styled-components
```

2023-08-03 22:11 UTC, akosasante commented on src/components/Contact.jsx
This looks great!

Will this component be used; or are you aiming to use it as a demo to show how to use the library?

I'm wondering if this PR can go ahead and wrap the `App.js` contents in the `ThemeProvider`, `Container`, and `CssBaseline` components so that subsequent PRs can start building with the outer layout already set?

2023-08-04 01:04 UTC, dayofthetech commented on package.json
> +    "@emotion/styled": "^11.11.0",
I think I'll keep styled components so I'll 

# uninstall emotion libraries
npm rm @emotion/react @emotion/styled

# install material ui styled-components helper
npm i -S @mui/styled-engine-sc

2023-08-04 01:05 UTC, dayofthetech commented on package.json
> +    "@emotion/styled": "^11.11.0",
I don't see the docs folder because when I cloned that was before it was created

2023-08-04 01:06 UTC, dayofthetech commented on src/components/Contact.jsx
This is a demo sample

2023-08-04 01:17 UTC, dayofthetech commented
I believed I was able to solve for the merge conflicts

2023-08-04 01:48 UTC, akosasante reviewed
Looking good! Your merge of main went well for the most part but I think it accidentally wiped away the changes in `package.json`. You can run the install steps again to install the MaterialUI and StyledComponents helper libraries, then commit and push that `package.json`. 

I think you should now also have the `docs` folder to write a blurb there. Or if you prefer you can do that as a follow up PR later 🙂

2023-08-08 01:10 UTC, dayofthetech commented
latest PR solves mui conflict

2023-08-08 01:11 UTC, dayofthetech reviewed
mui

2023-08-08 23:45 UTC, akosasante commented on public/index.html
> +    <meta name="viewport" content="initial-scale=1, width=device-width" />
I think this is already present on line 6

2023-08-08 23:45 UTC, akosasante approved these changes

2023-08-09 00:12 UTC, merged